################################################ system ################################################
device: ''  # cuda device, i.e. 0 or 0,1,2,3 or cpu
num_workers: 8  # dataloader threads. 0 for single-thread.
seed: 317  # random seed. From CornerNet 

################################################ database ################################################
use_database: False  # Flag to store data in InfluxDB
database_host: '' # IP address of the database
database_port: '' # port number of the database
database_name: '' # name of the Database

################################################ person detection ################################################
person_detection:
  enabled: True
  arch: yolo  # model architecture. Currently only supports yolo
  model_path: models/yolov5x6_mt_ft_ch.pt  # path to person detection pretrained model
  imgsz: [1280]  # inference size h,w
  inplace: True

################################################ vehicle detection ################################################
veh_detection:
  enabled: False
  arch: yolo  # model architecture. Currently only supports yolo
  model_path: models/yolov5n6.pt  # path to person detection pretrained model
  imgsz: [1280]  # inference size h,w
  inplace: True

################################################ image-based anomaly detection ################################################
img_anomaly_detection:
  enabled: True
  arch: mpn  # model architecture. Currently only supports mpn
  model_path: models/mpn_piazza_fiera_1.pt  # path to anomaly detection pretrained model
  h: 256  # height of input images
  w: 256  # width of input images
  t_length: 5  # length of the frame sequences
  alpha: 0.5  # weight for the anomality score
  c: 3
  psize: 10
  fdim: [128]
  pdim: [128]

################################################ trajectory-based anomaly detection ################################################
traj_anomaly_detection:
  enabled: False
  arch: ynet  # model architecture. Currently only supports yolo
  model_path: models/mt_trajnet_weights.pt  # path to trajectory forecasting pretrained model
  obs_len: 8  # past timesteps sampled at 2.5 fps
  pred_len: 12  # future timesteps sampled at 2.5 fps
  waypoints: [11]  # list of selected goal and waypoints as timestep idx, e.g. 14 means the 14th future timestep is used as a waypoint. Last element is goal timestep
  temperature: 1.0  
  num_goals: 20  # K_e
  num_traj: 1  # K_a
  resize: 1.0  # resize factor
  use_TTST: True  # use TTST
  rel_thresh: 0.01
  use_CWS: False  # use CWS
  segmentation_model_fp: null
  use_features_only: False
  semantic_classes: 0
  encoder_channels: [32, 32, 64, 64, 64]
  decoder_channels: [64, 64, 64, 32, 32]

################################################ tracking ################################################
tracking:
  enabled: False
  arch: fairmot  # model architecture. Currently only supports fairmot
  model_path: models/crowdhuman_dla34.pth  # path to tracking pretrained model
  down_ratio: 4  # output stride. Currently only supports 4
  input_res: -1  # input height and width. -1 for default from dataset. Will be overriden by input_h | input_w
  input_h: -1  # input height. -1 for default from dataset
  input_w: -1  # input width. -1 for default from dataset
  K: 500  # max number of output objects
  conf_thres: 0.4  # confidence thresh for tracking
  det_thres: 0.3  # confidence thresh for detection
  nms_thres: 0.4  # iou thresh for nms
  track_buffer: 30  # tracking buffer
  min_box_area: 100  # filter out tiny boxes
  reid_dim: 128  # feature dim for reid
  ltrb: True  # regress left, top, right, bottom of bbox
  reg_offset: True
  num_layers: 34
  head_conv: 256
  final_kernel: 1
  last_level: 5